const unitsRarity: { [key: string]: string } = {
  "740_1": "legend",
  "Izanami of Dusk": "legend",
  "733_1": "legend",
  "Daybreaker Izanagi": "legend",
  "Emperor Cat": "legend",
  "Kyosaka Nanaho": "legend",
  Akuma: "legend",
  "Gaia the Creator": "legend",
  "Doktor Heaven": "legend",
  Lumina: "legend",
  "Black Zeus": "legend",
  "Mighty Kristul Muu": "legend",
  Legeluga: "legend",
  "Wonder MOMOCO": "legend",
  Ushiwakamaru: "legend",
  "High Lord Babel": "legend",
  "Headmistress Jeanne": "legend",
  "Musashi Miyamoto": "legend",
  "Cake Machine": "uber",
  "756_1": "uber",
  "Akechi Mitsuhide": "uber",
  "Voluptuous Peony - Daji": "uber",
  "Floral Kalisa": "uber",
  "Frozen Rose Cat": "uber",
  "735_1": "uber",
  Pegasa: "uber",
  "Ninja Girl Tomoe": "uber",
  "Lightmother Aset": "uber",
  "Hatsune Miku XVI": "uber",
  "High School Kingpin Riki": "uber",
  Tekachi: "uber",
  "Mighty Sphinx Korps": "uber",
  "Coastal Explorer Kanna": "uber",
  Kaoluga: "uber",
  "Betrothed Balaluga": "uber",
  "Eva Unit-13": "uber",
  "One-Eyed Asuka": "uber",
  "King of Doom Phono": "uber",
  "Rabbit Satoru": "uber",
  "Thunder Jack": "uber",
  "White Butler Vigler": "uber",
  "Issun Boshi": "uber",
  "Child of Destiny Phono": "uber",
  "Reindeer Terun": "uber",
  "Goddess of Light Sirius": "uber",
  "Count Yukimura": "uber",
  "Spectral Goth Vega": "uber",
  Luke: "uber",
  Sakura: "uber",
  "Mighty Carrowsell": "uber",
  ネコチーター: "uber",
  "Ranma Saotome (Leotard)": "uber",
  "Cat Tengu": "uber",
  "Night Beach Lilin": "uber",
  "Chronos the Bride": "uber",
  "Sea Serpent Daliasan": "uber",
  "Iz the Dancer of Grief": "uber",
  Bliza: "uber",
  "Hattori Hanzo": "uber",
  "Lovestruck Lesser Demon": "uber",
  "Huntress Terun": "uber",
  "Sweet Love Mekako": "uber",
  "Lucifer the Fallen": "uber",
  "Iz the Dancer": "uber",
  "White Knight Cyclops": "uber",
  "Shitakiri Sparrow": "uber",
  "Mighty Deth-Troy-R": "uber",
  Yamii: "uber",
  Furiluga: "uber",
  "Kunio-kun": "uber",
  "Hevijak the Wicked": "uber",
  Lilin: "uber",
  "Shiro Amakusa": "uber",
  "Summoner Satoru": "uber",
  "Kaguya of the Coast": "uber",
  "Princess Cat": "uber",
  "Dark Aegis Garu": "uber",
  "Adventurer Kanna": "uber",
  "Mousse (Duck)": "uber",
  "Shampoo (Cat)": "uber",
  "Ryoga Hibiki (Pig)": "uber",
  "Akane Tendo": "uber",
  "Ranma Saotome (M)": "uber",
  "Blooming Kamukura": "uber",
  "Mighty Aethur Ltd.": "uber",
  "Snow Miku 2021": "uber",
  "First-Love Myrcia": "uber",
  "Sweet Aphrodite": "uber",
  "Baby Garu": "uber",
  "Keiji Claus": "uber",
  "Hatsune Miku: MM2020 Tokyo": "uber",
  "Hatsune Miku: MM2020 Osaka": "uber",
  "M. Bison": "uber",
  Sagat: "uber",
  Vega: "uber",
  Balrog: "uber",
  "E. Honda": "uber",
  "Skull Rider Vars": "uber",
  Gravi: "uber",
  Summerluga: "uber",
  "Squirtgun Saki": "uber",
  "Megurine Luka": "uber",
  "Hell Warden Emma": "uber",
  "Shaman Khan": "uber",
  "The 9th Angel": "uber",
  "The 10th Angel": "uber",
  "The 6th Angel": "uber",
  "The 4th Angel": "uber",
  "Night Oracle Rei": "uber",
  Papaluga: "uber",
  "Kasli the Bane": "uber",
  "Kagamine Rin & Len": "uber",
  "Sakura Miku": "uber",
  "Hatsune Miku": "uber",
  "Hades the Punisher": "uber",
  "Sharpshooter Saki": "uber",
  Herme: "uber",
  "Kasli the Scourge": "uber",
  "Snow Angel Twinstars": "uber",
  Kintaro: "uber",
  Lasvoss: "uber",
  Ken: "uber",
  Dhalsim: "uber",
  Blanka: "uber",
  Zangief: "uber",
  Guile: "uber",
  "Chun-Li": "uber",
  Ryu: "uber",
  Eyewaltz: "uber",
  "Relentless Gladios": "uber",
  Myrcia: "uber",
  "Narita Kaihime": "uber",
  "Seabreeze Coppermine": "uber",
  "AAA Wunder": "uber",
  "Eva Unit-08": "uber",
  Calette: "uber",
  "Li'l Valkyrie Dark": "uber",
  "Benevolent Souma": "uber",
  Heracrist: "uber",
  Satanmaria: "uber",
  "Super Devil": "uber",
  "Holy Phoenix": "uber",
  "Super Zeus": "uber",
  "Sakura Matou": "uber",
  "D'arktanyan": "uber",
  Bebe: "uber",
  "Empress Chronos": "uber",
  "Waverider Kuu": "uber",
  Nobiluga: "uber",
  "Li'l Valkyrie": "uber",
  "Detective Vigler": "uber",
  "Cat Clan Heroes": "uber",
  "Mighty Thermae D-Lux": "uber",
  "Moon Operators": "uber",
  "Shinji Cat": "uber",
  "Eva Unit-02": "uber",
  "Eva Unit-01": "uber",
  "Eva Unit-00": "uber",
  Voli: "uber",
  "Sakura Sonic": "uber",
  Ganglion: "uber",
  "Miyabi Oyama": "uber",
  "Subaru Hoshi": "uber",
  "Saki Nijima": "uber",
  "D'artanyan": "uber",
  "Dark Mitama": "uber",
  Gilgamesh: "uber",
  Rider: "uber",
  Lancer: "uber",
  Archer: "uber",
  Illyasviel: "uber",
  "Rin Tohsaka": "uber",
  Saber: "uber",
  Aer: "uber",
  Mizli: "uber",
  Bora: "uber",
  "Graveflower Verbena": "uber",
  "Wolfchild Deale": "uber",
  "Mighty Rekon Korps": "uber",
  "Seashore Kai": "uber",
  Twinstars: "uber",
  Todomeki: "uber",
  Michelia: "uber",
  "Lost World Yuki": "uber",
  "Imagawa Yoshimoto": "uber",
  "HMS Princess": "uber",
  "Queen Reika": "uber",
  "Sea Maiden Ruri": "uber",
  "Trickster Himeyuri": "uber",
  "Shadow Gao": "uber",
  "Bunny & Canard": "uber",
  "Springtime Kenshin": "uber",
  Mobius: "uber",
  Sarukani: "uber",
  "Miko Mitama": "uber",
  "Wrathful Poseidon": "uber",
  "Yuletide Nurse": "uber",
  "Mighty Bomburr": "uber",
  "Mighty Drednot": "uber",
  "Mighty Kat-A-Pult": "uber",
  "Lilith Cat": "uber",
  "Kyoko Sakura": "uber",
  "Mami Tomoe": "uber",
  "Sayaka Miki": "uber",
  "Homura Akemi": "uber",
  "Madoka Kaname": "uber",
  "Strike Unit R.E.I.": "uber",
  "Pai-Pai": "uber",
  "Midsummer Rabbit": "uber",
  "Tropical Kalisa": "uber",
  "Splendid Ganesha": "uber",
  "Shining Amaterasu": "uber",
  "Crazed Yuki": "uber",
  "Baby Gao": "uber",
  Hayabusa: "uber",
  "Radiant Aphrodite": "uber",
  "Anubis the Protector": "uber",
  "Thunder God Zeus": "uber",
  "Holy Coppermine": "uber",
  "Santa Kuu": "uber",
  "Frosty Kai": "uber",
  Togeluga: "uber",
  "Spooky Thundia": "uber",
  Hallowindy: "uber",
  "Warlock and Pierre": "uber",
  "HI-DO": "uber",
  "DONALD MORDEN": "uber",
  "JUPITER KING": "uber",
  "HUGE HERMIT": "uber",
  "The White Rabbit": "uber",
  "Kachi-Kachi": "uber",
  Catman: "uber",
  "Mekako Saionji": "uber",
  Akira: "uber",
  Mystica: "uber",
  Juvens: "uber",
  Cornelia: "uber",
  Hearscht: "uber",
  "Mystery Girl Yuki": "uber",
  Dioramos: "uber",
  "Mola King": "uber",
  Balaluga: "uber",
  Tecoluga: "uber",
  Kubiluga: "uber",
  Asiluga: "uber",
  "Crazed Princess Punt": "uber",
  Kalisa: "uber",
  "Uesugi Kenshin": "uber",
  "Nurse Cat": "uber",
  "Princess Kaguya": "uber",
  "Kasa Jizo": "uber",
  Momotaro: "uber",
  "The Grateful Crane": "uber",
  "Urashima Taro": "uber",
  "Takeda Shingen": "uber",
  "Date Masamune": "uber",
  Wyvern: "uber",
  Coppermine: "uber",
  Kai: "uber",
  Kuu: "uber",
  Raiden: "uber",
  Kamukura: "uber",
  Vars: "uber",
  Megidora: "uber",
  Sodom: "uber",
  Thundia: "uber",
  Windy: "uber",
  "Oda Nobunaga": "uber",
  "Maeda Keiji": "uber",
  "Sanada Yukimura": "uber",
  PPT48: "uber",
  "Baby Cat": "uber",
  "Marauder Cat": "uber",
  "Evangelist Cat": "uber",
  "Lesser Demon Cat": "uber",
  "Cat Machine": "uber",
  "Ice Cat": "uber",
  Nekoluga: "uber",
  "Ancient Egg: N111": "super",
  "Ancient Egg: N108": "super",
  "Brainwashed Titan Cat": "super",
  "Brainwashed Lizard Cat": "super",
  "Brainwashed Fish Cat": "super",
  "Genma Saotome (Panda)": "super",
  "Brainwashed Bird Cat": "super",
  "Brainwashed Cow Cat": "super",
  "Brainwashed Gross Cat": "super",
  "Brainwashed Axe Cat": "super",
  "Brainwashed Tank Cat": "super",
  "Brainwashed Cat": "super",
  "Tatewaki Kuno (Gi)": "super",
  "Ukyo Kuonji (GR)": "super",
  Happosai: "super",
  "KAITO & Cat": "super",
  "Valentine's Neneko": "super",
  "C. Honda": "super",
  "Lifeguard Cats": "super",
  "Suntan Cat": "super",
  "MEIKO & Cat": "super",
  "Holy Knight Alibaba": "super",
  "Nymph Cat": "super",
  "Good-Luck Ebisu": "super",
  "Rei Ayanami (???)": "super",
  "Ritsuko Akagi": "super",
  "Misato Katsuragi": "super",
  Hina: "super",
  "Fiendish Nero": "super",
  "Kotomine & Gilgamesh Cats": "super",
  "Miter Saw Cat": "super",
  "Backhoe Cat": "super",
  "Cutter Cat": "super",
  "Piledriver Cat": "super",
  "Driller Cat": "super",
  "Otaku Geek Cat": "super",
  "Mari Illustrious": "super",
  "Asuka Langley": "super",
  "Rei Ayanami": "super",
  "Hijiri Rokudo": "super",
  "Mizuki Tachibana": "super",
  "Aoi Hayakawa": "super",
  "Fencer Cat": "super",
  Orthos: "super",
  "Easter Neneko": "super",
  Belial: "super",
  "Years-End Neneko": "super",
  "Vaulter Cat": "super",
  Kyubey: "super",
  "Little Leaguer Cat": "super",
  "Express Cat": "super",
  "Sunny Neneko": "super",
  "Cheerleader Cat": "super",
  Catornado: "super",
  Catway: "super",
  "Sniper the Recruit": "super",
  "Rich Cat III": "super",
  "Freshman Cat Jobs": "super",
  "Gloomy Neneko": "super",
  "ALLEN O'NEIL": "super",
  "SV-001": "super",
  "Metal Cat": "super",
  "Surfer Cat": "super",
  Citrouille: "super",
  Alois: "super",
  "Baby Mola": "super",
  Yurinchi: "super",
  "Cat Toaster": "super",
  "Figure Skating Cats": "super",
  "Weightlifter Cat": "super",
  "Juliet Cat": "super",
  "Cat Base Mini": "super",
  Neneko: "super",
  "Gold Cat": "super",
  Rei: "super",
  Aura: "super",
  "Crazed Titan Cat": "super",
  "Crazed Lizard Cat": "super",
  "Crazed Fish Cat": "super",
  "Crazed Bird Cat": "super",
  "Crazed Cow Cat": "super",
  "Crazed Gross Cat": "super",
  "Crazed Axe Cat": "super",
  "Crazed Tank Cat": "super",
  "Crazed Cat": "super",
  "Sleeping Beauty Punt": "super",
  Reaper: "super",
  "Sushi Cat": "super",
  "Bath Cat": "super",
  "Apple Cat": "super",
  "Swimmer Cat": "super",
  "Nerd Cat": "super",
  "Kotatsu Cat": "super",
  "Hip Hop Cat": "super",
  "Delinquent Cat": "super",
  "Bodhisattva Cat": "super",
  Madhead: "rare",
  "Mollyanna Cat": "rare",
  "Ancient Egg: N112": "rare",
  "Maize Cat": "rare",
  "Ancient Egg: N110": "rare",
  "Jetpack Cat": "rare",
  "Ancient Egg: N109": "rare",
  "Ancient Egg: N107": "rare",
  "Killer Tank Cat": "rare",
  "Yuma Kuga & Cat": "rare",
  "Osamu Mikumo & Cat": "rare",
  "Ancient Egg: N106": "rare",
  "Ancient Egg: N105": "rare",
  "Ancient Egg: N104": "rare",
  "Ancient Egg: N103": "rare",
  "Ancient Egg: N102": "rare",
  "Ancient Egg: N101": "rare",
  "Calligraphy Cat": "rare",
  "Pied Piper Cat": "rare",
  "Aku Researcher": "rare",
  "Godzilla Cat": "rare",
  "Akane Cat": "rare",
  "Ranma Cat (M)": "rare",
  "Neko Len": "rare",
  "Neko Rin": "rare",
  "Stone Cat": "rare",
  "M. Bison Cat": "rare",
  "Sagat Cat": "rare",
  "Vega Cat": "rare",
  "Balrog Cat": "rare",
  "Luka Cat": "rare",
  "Bakery Cat": "rare",
  "Kaworu Cat": "rare",
  "Phantom Cat": "rare",
  "Rugby Cat": "rare",
  "Miku Cat": "rare",
  "Teacher BearCat": "rare",
  "Cossack Cat": "rare",
  "Slime Cat": "rare",
  "Wushu Cat": "rare",
  "Medusa Cat": "rare",
  "Akuma Giraffe": "rare",
  "Ryu Cat": "rare",
  Mightycat: "rare",
  "Cat Bros": "special",
  "Matador Cat": "rare",
  "Kano ＆ Souma": "rare",
  "Prince Yamato": "rare",
  "Rider the Cat": "rare",
  "Archer the Cat": "rare",
  "Primordial Cat": "rare",
  "Lone Cat and Kitten": "rare",
  Betakkuma: "rare",
  "Souma Cat": "rare",
  Coco: "rare",
  Ovis: "rare",
  Pokota: "rare",
  "Mari Cat": "rare",
  "Asuka Cat": "rare",
  "Rei Cat": "rare",
  "Giraffe Unit-01": "rare",
  "Shinji & Cat": "rare",
  Mentori: "rare",
  "Karin Nekozuka": "rare",
  "Ren Katagiri": "rare",
  "Misaki Konno": "rare",
  "Sairi Nijitani": "rare",
  "Akio Yabe": "rare",
  "Glass Cat": "rare",
  "Volley Cat": "rare",
  "Rover Cat": "rare",
  "Li'l Shirou": "rare",
  "Illya the Cat": "rare",
  "Rin the Cat": "rare",
  "Sakura the Cat": "rare",
  "Slug Jockey Cat": "rare",
  "Redhead Yuki Cat": "rare",
  "Eggy Cat": "rare",
  "Welterweight Cat": "rare",
  "Curling Cat": "rare",
  "Killer Cat": "rare",
  PIKOTARO: "rare",
  "Gardener Cat": "rare",
  "Food Stall Cat": "rare",
  "Kyubey Cat": "rare",
  "Li'l Madoka": "rare",
  "Kyoko Cat": "rare",
  "Mami Cat": "rare",
  "Sayaka Cat": "rare",
  "Homura Cat": "rare",
  "Madoka Cat": "rare",
  "Awa-Odori Cat": "rare",
  Funghi: "rare",
  "A Gift of Cats": "rare",
  Pumpcat: "rare",
  "MARS PEOPLE": "rare",
  FIO: "rare",
  ERI: "rare",
  TARMA: "rare",
  MARCO: "rare",
  HYAKUTARO: "rare",
  "Drumcorps Cat": "rare",
  "Onmyoji Cat": "rare",
  Psychocat: "rare",
  "Cat Kart R": "rare",
  "Takuya ＆ Yuki": "rare",
  "Marshmallow Cat": "rare",
  "Hoop Cat": "rare",
  "Mer-Cat": "rare",
  "Rocker Cat": "rare",
  "Tin Cat": "rare",
  "Stilts Cat": "rare",
  "Cat Gunslinger": "rare",
  "Kung Fu Cat X": "rare",
  "Vengeful Cat": "rare",
  "Clockwork Cat": "rare",
  "Vacation Queen": "rare",
  Fuu: "rare",
  Serum: "rare",
  Yoichi: "rare",
  Norn: "rare",
  Olga: "rare",
  Nono: "rare",
  Celesse: "rare",
  "Madam Bride": "rare",
  "Koi Cat": "rare",
  "Maiden Cat": "rare",
  "Rope Jump Cat": "rare",
  "Doll Cats": "rare",
  "Evil Cat": "rare",
  "Adult Cat": "rare",
  "Space Cat": "rare",
  "Droid Cat": "rare",
  "Reindeer Fish Cat": "rare",
  "Salaryman Cat": "rare",
  "Li'l Gau": "rare",
  "Cow Princess": "rare",
  Swordsman: "rare",
  "Sports Day Cat": "rare",
  "Bronze Cat": "rare",
  "Swordsman Cat": "rare",
  "Archer Cat": "rare",
  "Witch Cat": "rare",
  "Shaman Cat": "rare",
  "Fortune Teller Cat": "rare",
  "Bishop Cat": "rare",
  "Thief Cat": "rare",
  "Pirate Cat": "rare",
  "Viking Cat": "rare",
  "Jurassic Cat": "rare",
  "Salon Cat": "rare",
  "Wheel Cat": "rare",
  "Pogo Cat": "rare",
  "Ancient Egg: N205": "special",
  "Dotty Cat": "special",
  "Felix the Cat Duke Cat": "special",
  "Trash Cat": "special",
  "Principal Cat": "special",
  "730_1": "special",
  "Master of Mind Soractes": "special",
  "Ancient Egg: N006": "special",
  "Ancient Egg: N203": "special",
  "Ancient Egg: N005": "special",
  "Class Rep Cat": "special",
  "Ancient Egg: N000": "special",
  "Ancient Egg: N004": "special",
  "Chika Amatori & Cat": "special",
  "Ancient Egg: N202": "special",
  "Ancient Egg: N003": "special",
  "Ancient Egg: N201": "special",
  "Ancient Egg: N001": "special",
  "Elder Beast Naala": "special",
  "Chalkboard Eraser Cat": "special",
  "Tomboy Lion Cat": "special",
  "Secret Crush Cat": "special",
  "Firecracker Cat": "special",
  "Million-Dollar Cat": "special",
  "Jagando Jr.": "special",
  "Kuwagata Cat": "special",
  "Kabuto Cat": "special",
  "Elder Mask Doron": "special",
  "Gold Brick Cat": "special",
  "Panda Cat": "special",
  "Idi:N": "special",
  "Gacha Cat": "special",
  "Heavenly Jack": "special",
  "Master Uril": "special",
  "Urs & Fenrir": "special",
  "Chun-Li Cat": "special",
  "Shakurel Panda": "special",
  "Shakurel Tiger": "special",
  "Shakurel Lion": "special",
  "Shakurel Cat": "special",
  Nekonosuke: "special",
  "Cat Devil": "special",
  "Wakamiko Cat": "special",
  "Rosary Angel": "special",
  Dogumaru: "special",
  "Filibuster Cat X": "special",
  "Shirou the Cat": "special",
  "Cat God the Great": "special",
  Nekokkuma: "special",
  "Mecha-Bun": "special",
  "Crazed Moneko": "special",
  "Kaworu & Cat": "special",
  "Gendo & Fuyutsuki Cats": "special",
  Imoto: "special",
  "Satori Hikami & Cat": "special",
  "Masked Yulala": "special",
  "Farmer Cat": "special",
  "Coin Cat": "special",
  "Li'l Sakura": "special",
  "Saber the Cat": "special",
  "Hermit Cat": "special",
  "Maneki Cat": "special",
  "Happy 100": "special",
  "Miyamoku Musashi": "special",
  CPAC: "special",
  "Li'l Titan Cat": "special",
  "Li'l Lizard Cat": "special",
  "Li'l Fish Cat": "special",
  "Li'l Homura": "special",
  Fortressy: "special",
  "White Cat": "special",
  Tanky: "special",
  "Red Riding Mina": "special",
  "Undead Cat": "special",
  "Li'l Bird Cat": "special",
  "Li'l Cow Cat": "special",
  "Li'l Gross Cat": "special",
  Catburger: "special",
  "Li'l Axe Cat": "special",
  "Li'l Tank Cat": "special",
  "Li'l Cat": "special",
  "Baozi Cat": "special",
  Titi: "special",
  "Mr. Ninja": "special",
  "Yuki Cat": "special",
  "Meowla Meowla": "special",
  "Li'l Nyandam": "special",
  God: "special",
  "Squish Ball Cat": "special",
  "Ururun Wolf": "special",
  "Flower Cat": "special",
  "Bean Cats": "special",
  Merc: "special",
  Healer: "special",
  "Cabaret Cat": "special",
  "Blue Shinobi": "special",
  "Toy Machine Cat": "special",
  "Maiko Cat": "special",
  "Masked Cat": "special",
  "Capsule Cat": "special",
  "Cat Princess": "special",
  Kerihime: "special",
  "Bahamut Cat": "special",
  "Valkyrie Cat": "special",
  "Skirt Cat": "special",
  "Boogie Cat": "special",
  "Sumo Cat": "special",
  "Samurai Cat": "special",
  "Zombie Cat": "special",
  "Ninja Cat": "special",
  "Tricycle Cat": "special",
  Moneko: "special",
  "Panties Cat": "special",
  "Cats in a Box": "special",
  "Dom Cat": "special",
  "Bondage Cat": "special",
  "Mr.": "special",
  "Kung Fu Cat": "special",
  "Actress Cat": "special",
  Superfeline: "normal",
  "Titan Cat": "normal",
  "Lizard Cat": "normal",
  "Fish Cat": "normal",
  "Bird Cat": "normal",
  "Cow Cat": "normal",
  "Gross Cat": "normal",
  "Axe Cat": "normal",
  "Tank Cat": "normal",
  Cat: "normal",
};

export default class UnitsRarity {
  getRarity(unitName: string): string {
    return unitsRarity[unitName] || "unknown";
  }
}
